# $Id: Makefile.in,v 1.1.2.6 2002/12/12 21:29:04 jnelson Exp $

COMMON_CFLAGS =

ifeq ($(wildcard $(DIR_LINUX)/.config),)
COMMON_CFLAGS += -DKERNEL_2_6_30
else
KERNEL_VER=$(patsubst $(DIR_ROOT)/%,%,$(DIR_LINUX))
ifeq ($(KERNEL_VER),linux-2.6.30)
COMMON_CFLAGS += -DKERNEL_2_6_30
endif
ifeq ($(KERNEL_VER),linux-3.10)
COMMON_CFLAGS += -DKERNEL_3_10
endif
ifeq ($(KERNEL_VER),linux-3.2)
COMMON_CFLAGS += -DKERNEL_3_2
endif
ifeq ($(KERNEL_VER),linux-2.6.36.x)
COMMON_CFLAGS += -DKERNEL_2_6_36_X
endif
include $(DIR_LINUX)/.config
endif

ifeq ($(wildcard $(DIR_USERS)/.config),)
include .config
else
include $(DIR_USERS)/.config
endif

ifdef CONFIG_RTL_JFFS2_PARTITION_ENABLE
ifdef CONFIG_JFFS2_FS
ifneq ($(CONFIG_RTL_JFFS2_FILE_PARTITION_SIZE),0x0)
COMMON_CFLAGS += -DCONFIG_RTL_JFFS2_FILE_PARTITION
else
$(error "Please set JFFS2 file partition size in System Configuration!")
endif
else
$(error "Please select JFFS2_FS!")
endif
else
ifneq ($(CONFIG_RTL_CWMP_TRANSFER_PARTITION_SIZE),0x0)
COMMON_CFLAGS += -DCONFIG_RTL_CWMP_TRANSFER_PARTITION
endif
ifneq ($(CONFIG_RTL_CWMP_NOTIFICATION_PARTITION_SIZE),0x0)
COMMON_CFLAGS += -DCONFIG_RTL_CWMP_NOTIFICATION_PARTITION
endif
ifneq ($(CONFIG_RTL_CWMP_CACERT_PARTITION_SIZE),0x0)
COMMON_CFLAGS += -DCONFIG_RTL_CWMP_CACERT_PARTITION
endif
endif

ifeq ($(CONFIG_MTD_NAME_MAPPING),y)
COMMON_CFLAGS += -DMTD_NAME_MAPPING
endif

ifdef CONFIG_RTL_8198_AP_ROOT
CONFIG_RTL_AP = CONFIG_RTL_8198_AP_ROOT
endif

ifdef CONFIG_RTL_8197D_AP
CONFIG_RTL_AP = CONFIG_RTL_8197D_AP
endif

ifdef CONFIG_RTL_AP
AP=1
SKUTAG=ap
else
GW=1
SKUTAG=gw
endif
#------------------------------------------------------------------------------
# APMIB_SHARED, APMIB_LIB and COMMON_CFLAGS
#------------------------------------------------------------------------------
APMIB_SHARED = 1
DYNAMIC_WAN_IP = 1
GET_SERVER_IP_BY_DOMAIN = 1
#COMMON_CFLAGS =
ifeq ($(x86),1)
COMMON_CFLAGS += -DNO_ACTION
endif

ifeq ($(APMIB_SHARED),1)
COMMON_CFLAGS += -DCONFIG_APMIB_SHARED
APMIB_LIB = libapmib.so
else
APMIB_LIB = libapmib.a
endif

# User Management switch
UMSW	= -DUSER_MANAGEMENT_SUPPORT

# TLS client mode support
#TLS= -DTLS_CLIENT


# WLAN support
#-DWLAN_EASY_CONFIG
WLANSUPP = -DUNIVERSAL_REPEATER -DWLAN_WPA -DWLAN_WDS -DWLAN_8185AG -DWLAN_WPA2 $(TLS)
WLANSUPP += -DWIFI_SIMPLE_CONFIG

ifeq ($(CONFIG_MULTIPLE_WAN_SUPPORT),y)
COMMON_CFLAGS += -D MULTI_WAN_SUPPORT
COMMON_CFLAGS += -D MULTI_WAN_FIREWALL
COMMON_CFLAGS += -D FIREWALL_MULTICHAIN
endif

ifeq ($(CONFIG_MULTIPLE_WAN_SUPPORT),y)
ifeq ($(CONFIG_SINGLE_WAN_SUPPORT),y)
COMMON_CFLAGS += -D SINGLE_WAN_SUPPORT
endif
endif

ifeq ($(CONFIG_RTL_11W_SUPPORT), y)
WLANSUPP += -DCONFIG_IEEE80211W
endif

ifeq ($(CONFIG_APP_SIMPLE_CONFIG), y)
WLANSUPP += -DCONFIG_APP_SIMPLE_CONFIG
COMMON_CFLAGS += -DSET_MIB_FROM_FILE
ifeq ($(CONFIG_SIMPLE_CONFIG_SYNC_VXD_PROFILE), y)
COMMON_CFLAGS += -DSYNC_VXD_PROFILE
endif
else
ifeq ($(CONFIG_APP_RTK_INBAND_CTL), y)
COMMON_CFLAGS += -DSET_MIB_FROM_FILE
COMMON_CFLAGS += -DCONFIG_APP_RTK_INBAND_CTL

endif
endif
ifeq ($(CONFIG_RTL_HS2_SUPPORT), y)
WLANSUPP += -DWLAN_HS2_CONFIG
endif

# Digest Access switch
DASW	= -DDIGEST_ACCESS_SUPPORT

# Gateway flag
GATEWAY = -DHOME_GATEWAY -DDOS_SUPPORT
ifeq ($(GW),1)
GATEWAY += -DROOT_FS
endif

# samba web support
ifeq ($(CONFIG_APP_SAMBA_WEB), y)
COMMON_CFLAGS += -DSAMBA_WEB_SUPPORT
endif
ifeq ($(CONFIG_URL_FILTER_USER_MODE_SUPPORT),y)
COMMON_CFLAGS += -DURL_FILTER_USER_MODE_SUPPORT
endif

# routing support
ifeq ($(CONFIG_APP_ROUTED), y)
COMMON_CFLAGS += -DROUTE_SUPPORT
endif
ifeq ($(CONFIG_APP_AP_CONTROLER), y)
COMMON_CFLAGS += -DAP_CONTROLER_SUPPORT
endif
ifeq ($(CONFIG_APP_BIRD), y)
COMMON_CFLAGS += -DRIP6_SUPPORT
endif

ifeq ($(CONFIG_APP_UPDATEDD), y)
COMMON_CFLAGS += -DDDNS_SUPPORT
endif

ifeq ($(CONFIG_APP_PPTP), y)
COMMON_CFLAGS += -DPPTP_SUPPORT
endif

ifeq ($(CONFIG_APP_L2TPD), y)
COMMON_CFLAGS += -DL2TP_SUPPORT
endif

ifeq ($(CONFIG_RTL_DEF_SETTING_IN_FW),y)
COMMON_CFLAGS += -DRTL_DEF_SETTING_IN_FW
ifeq ($(CONFIG_RTL_DEFSETTING_AUTO_UPDATE),y)
COMMON_CFLAGS += -DDEFSETTING_AUTO_UPDATE
endif
endif

# boa cgi support
#export BOA_CGI_SUPPORT=y
ifeq ($(BOA_CGI_SUPPORT), y)
COMMON_CFLAGS += -DBOA_CGI_SUPPORT
endif

ifeq ($(CONFIG_RTL_11R_SUPPORT),y)
COMMON_CFLAGS += -DFAST_BSS_TRANSITION
endif
ifeq ($(DYNAMIC_WAN_IP), 1)
COMMON_CFLAGS += -DCONFIG_DYNAMIC_WAN_IP
ifeq ($(GET_SERVER_IP_BY_DOMAIN), 1)
COMMON_CFLAGS += -DCONFIG_GET_SERVER_IP_BY_DOMAIN
endif
endif

ifeq ($(CONFIG_MTD_NAND),y)
ifeq ($(CONFIG_RTK_NAND_FLASH_STORAGE),)
COMMON_CFLAGS += -DCONFIG_MTD_NAND
endif
endif

ifeq ($(CONFIG_SYSFS),y)
COMMON_CFLAGS += -DCONFIG_SYSFS
endif

ifeq ($(CONFIG_RPS),y)
COMMON_CFLAGS += -DCONFIG_RPS
endif

ifeq ($(CONFIG_RTK_VLAN_SUPPORT),y)
COMMON_CFLAGS += -DVLAN_CONFIG_SUPPORTED
endif
ifeq ($(CONFIG_RTL_DNS_TRAP),y)
COMMON_CFLAGS += -DCONFIG_RTL_DNS_TRAP
endif
ifeq ($(CONFIG_RTL_HTTP_REDIRECT_TR098),y)
COMMON_CFLAGS += -DCONFIG_RTL_HTTP_REDIRECT_TR098
COMMON_CFLAGS += -D_SUPPORT_CAPTIVEPORTAL_PROFILE_
endif
ifeq ($(CONFIG_RTL_VLAN_8021Q),y)
COMMON_CFLAGS += -DCONFIG_8021Q_VLAN_SUPPORTED
endif
ifeq ($(CONFIG_RTL_8021Q_VLAN_SUPPORT_SRC_TAG),y)
COMMON_CFLAGS += -DCONFIG_RTL_8021Q_VLAN_SUPPORT_SRC_TAG
endif
ifeq ($(CONFIG_RTL_MULTICAST_PORT_MAPPING),y)
COMMON_CFLAGS += -DCONFIG_RTL_MULTICAST_PORT_MAPPING
endif
ifeq ($(CONFIG_RTL_SUPPORT_ACCESS_PORT_FORWARD_FROM_LAN),y)
COMMON_CFLAGS += -DCONFIG_RTL_SUPPORT_ACCESS_PORT_FORWARD_FROM_LAN
endif

ifeq ($(CONFIG_RTL_REDIRECT_ACL_SUPPORT_FOR_ISP_MULTI_WAN),y)
COMMON_CFLAGS += -DCONFIG_RTL_REDIRECT_ACL_SUPPORT_FOR_ISP_MULTI_WAN
endif

COMMON_CFLAGS += -DCONFIG_RTL_WEB_WAN_ACCESS_PORT

#ifeq ($(CONFIG_APP_TR069),y)
COMMON_CFLAGS += -DCONFIG_RTL_PORTFW_EXTEND
#endif

ifeq ($(CONFIG_RTL_ULINKER),y)
COMMON_CFLAGS += -DCONFIG_RTL_ULINKER
endif

ifeq ($(CONFIG_RTL_STA_CONTROL_SUPPORT),y)
COMMON_CFLAGS += -DSTA_CONTROL
endif

ifeq ($(CONFIG_RTL_DOT11K_SUPPORT),y)
COMMON_CFLAGS += -DDOT11K
endif

ifeq ($(CONFIG_RTL_MESH_SUPPORT),y)
        MESH_EXTRA_CONFIG_FLAGS += -DCONFIG_RTK_MESH -D_MESH_ACL_ENABLE_ -DCONFIG_NEW_MESH_UI
endif
export MESH_EXTRA_CONFIG_FLAGS

WLANSUPP += $(MESH_EXTRA_CONFIG_FLAGS)

# RTK Airtime Fairness UI
ifeq ($(CONFIG_RTL_ATM_SUPPORT), y)
#WLANSUPP += -DWLAN_ATM_CONFIG
WLANSUPP += -DCONFIG_RTL_AIRTIME
endif

ifeq ($(CONFIG_RTL8192CD),y)
        WLANSUPP += -DCONFIG_RTL8192CD
endif

ifeq ($(CONFIG_RTL8196B_GW_8M),y)
WLANSUPP += -DCONFIG_RTL8196B_GW_8M
endif

COMMON_CFLAGS += $(WLANSUPP) $(UMSW) $(DASW) -DDOWN_SIZE

ifdef CONFIG_DEFAULTS_KERNEL_2_6
COMMON_CFLAGS += -DCONFIG_DEFAULTS_KERNEL_2_6
endif

ifeq ($(CONFIG_APP_USBMOUNT),y)
COMMON_CFLAGS += -DCONFIG_APP_USBMOUNT
endif

ifeq ($(CONFIG_RTL_HIGH_PERFORMANCE_FILESYSTEM),y)
COMMON_CFLAGS += -DCONFIG_RTL_HIGH_PERFORMANCE_FILESYSTEM
endif

ifeq ($(CONFIG_USBDISK_UPDATE_IMAGE),y)
COMMON_CFLAGS += -DCONFIG_USBDISK_UPDATE_IMAGE
endif

ifeq ($(CONFIG_APP_SAMBA),y)
COMMON_CFLAGS += -DCONFIG_APP_SAMBA 
endif
ifeq ($(CONFIG_APP_SAMBA-3.6.24),y)
COMMON_CFLAGS += -DCONFIG_APP_SAMBA_3_6_24
endif
ifeq ($(CONFIG_APP_VSFTPD),y)
COMMON_CFLAGS += -DCONFIG_APP_VSFTPD
endif

ifeq ($(CONFIG_APP_DLNA_DMS),y)
COMMON_CFLAGS += -DCONFIG_APP_DLNA_DMS
endif

ifeq ($(CONFIG_APP_CTORRENT), y)
COMMON_CFLAGS += -DCONFIG_RTL_BT_CLIENT
endif

ifeq ($(CONFIG_APP_TRANSMISSION), y)
COMMON_CFLAGS += -DCONFIG_RTL_TRANSMISSION
endif

ifeq ($(CONFIG_APP_SNMP),y)
COMMON_CFLAGS += -DCONFIG_SNMP
endif

ifeq ($(CONFIG_RTL_IVL_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_IVL_SUPPORT
endif

ifeq ($(CONFIG_RTL_FLASH_DUAL_IMAGE_ENABLE),y)
COMMON_CFLAGS += -DCONFIG_RTL_FLASH_DUAL_IMAGE_ENABLE 
endif

ifeq ($(CONFIG_RTL_FLASH_DUAL_IMAGE_WEB_BACKUP_ENABLE),y)
COMMON_CFLAGS += -DCONFIG_RTL_FLASH_DUAL_IMAGE_WEB_BACKUP_ENABLE
endif

ifeq ($(CONFIG_RTK_WLAN_EVENT_INDICATE),y)
COMMON_CFLAGS += -DCONFIG_RTK_EVENTD_SUPPORT
endif

ifeq ($(CONFIG_APP_RTK_EVENTD_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTK_EVENTD_SUPPORT 
endif

ifeq ($(CONFIG_RTL_MULTI_REPEATER_MODE_SUPPORT),y)
COMMON_CFLAGS += -DRTL_MULTI_REPEATER_MODE_SUPPORT
endif

ifeq ($(CONFIG_RTL_MULTI_CLONE_SUPPORT),y)
COMMON_CFLAGS += -DRTL_MULTI_CLONE_SUPPORT
endif

ifeq ($(CONFIG_USB_SERIAL_OPTION),y)
COMMON_CFLAGS += -DRTK_USB3G
#ifeq ($(CONFIG_POCKET_ROUTER_SUPPORT),y)
#COMMON_CFLAGS += -DRTK_USB3G_PORT5_LAN
#endif
endif

ifeq ($(CONFIG_4G_LTE_SUPPORT), y)
COMMON_CFLAGS += -DCONFIG_4G_LTE_SUPPORT
endif

#CONFIG_RTL_DUAL_PCIESLOT_BIWLAN_D
#ifeq ($(CONFIG_RTL_DUAL_PCIESLOT_BIWLAN_D),y)
ifeq ($(CONFIG_USE_PCIE_SLOT_0),y)
ifeq ($(CONFIG_USE_PCIE_SLOT_1),y)
ifeq ($(CONFIG_RTL_92D_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_92D_DMDP  -DCONFIG_RTL_DUAL_PCIESLOT_BIWLAN_D -DFOR_DUAL_BAND
endif
endif
endif
ifeq ($(CONFIG_RTL_P2P_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_P2P_SUPPORT
endif

ifeq ($(CONFIG_RTL_92D_DMDP),y)
COMMON_CFLAGS += -DFOR_DUAL_BAND
endif

ifeq ($(CONFIG_WLAN_HAL_8881A),y)
ifeq ($(CONFIG_RTL_8881A_SELECTIVE),y)
COMMON_CFLAGS += -DCONFIG_RTL_8881A_SELECTIVE
else
COMMON_CFLAGS += -DCONFIG_RTL_92D_SUPPORT
endif
COMMON_CFLAGS += -DCONFIG_RTL_8812_SUPPORT
COMMON_CFLAGS += -DCONFIG_RTL_11AC_SUPPORT

ifeq ($(CONFIG_USE_PCIE_SLOT_0),y)
COMMON_CFLAGS += -DFOR_DUAL_BAND
COMMON_CFLAGS += -DCONFIG_RTL_DUAL_PCIESLOT_BIWLAN_D
endif
endif

ifeq ($(CONFIG_WLAN_HAL_8814AE),y)
COMMON_CFLAGS += -DCONFIG_WLAN_HAL_8814AE
COMMON_CFLAGS += -DCONFIG_RTL_8881A_SELECTIVE
COMMON_CFLAGS += -DCONFIG_RTL_8812_SUPPORT
COMMON_CFLAGS += -DCONFIG_RTL_11AC_SUPPORT
ifeq ($(CONFIG_USE_PCIE_SLOT_0),y)
ifeq ($(CONFIG_USE_PCIE_SLOT_1),y)
COMMON_CFLAGS += -DCONFIG_RTL_92D_SUPPORT
COMMON_CFLAGS += -DCONFIG_RTL_DUAL_PCIESLOT_BIWLAN
COMMON_CFLAGS += -DCONFIG_RTL_DUAL_PCIESLOT_BIWLAN_D
COMMON_CFLAGS += -DFOR_DUAL_BAND
endif
endif
endif

ifeq ($(CONFIG_WLAN_HAL_8197F),y)
COMMON_CFLAGS += -DCONFIG_WLAN_HAL_8197F
ifeq ($(CONFIG_USE_PCIE_SLOT_0),y)
COMMON_CFLAGS += -DCONFIG_RTL_92D_SUPPORT
COMMON_CFLAGS += -DFOR_DUAL_BAND
COMMON_CFLAGS += -DCONFIG_RTL_DUAL_PCIESLOT_BIWLAN_D
endif
endif

#ifeq ($(CONFIG_RTL_DUAL_92C_8812E),y)
ifeq ($(CONFIG_USE_PCIE_SLOT_0),y)
ifeq ($(CONFIG_USE_PCIE_SLOT_1),y)
#ifeq ($(CONFIG_RTL_8812_SUPPORT),y)
COMMON_CFLAGS += -DFOR_DUAL_BAND
COMMON_CFLAGS += -DCONFIG_RTL_92D_SUPPORT
COMMON_CFLAGS += -DCONFIG_RTL_DUAL_PCIESLOT_BIWLAN_D
#endif
endif
endif
ifeq ($(CONFIG_USE_PCIE_SLOT_0),y)                                                            
ifeq ($(CONFIG_USE_PCIE_SLOT_1),y)                                                            
ifeq ($(CONFIG_RTL_8367R_SUPPORT),y)
COMMON_CFLAGS += -DRTL_8367R_DUAL_BAND
endif
endif
endif

ifeq ($(CONFIG_USE_PCIE_SLOT_0),y)
ifeq ($(CONFIG_RTL_8881A),y)
ifeq ($(CONFIG_RTL_8367R_SUPPORT),y)
COMMON_CFLAGS += -DRTL_8367R_8881a_DUAL_BAND
endif
endif
endif

ifeq ($(CONFIG_RTL_IPV6READYLOGO),y)
ifeq ($(CONFIG_RTL_8367R_SUPPORT),y)
COMMON_CFLAGS += -DRTL_8367R_IPV6READY_LOGO
endif
endif

ifeq ($(CONFIG_SLOT_0_8192EE),y)
COMMON_CFLAGS += -DCONFIG_RTL8192E
endif
ifeq ($(CONFIG_SLOT_1_8192EE),y)
COMMON_CFLAGS += -DCONFIG_RTL8192E
endif


ifeq ($(CONFIG_RTL_8812_SUPPORT),y)
COMMON_CFLAGS += -DSUPPORT_TX_AMSDU
endif
ifeq ($(CONFIG_WLAN_HAL_8814AE),y)
COMMON_CFLAGS += -DSUPPORT_TX_AMSDU
endif
#
# Extra Feature Configuration
#
ifeq ($(CONFIG_HTTP_FILE_SERVER_SUPPORT),y)
COMMON_CFLAGS += -DHTTP_FILE_SERVER_SUPPORTED
COMMON_CFLAGS += -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DENABLE_LFS
COMMON_CFLAGS += -DHTTP_FILE_SERVER_HTM_UI
endif
ifeq ($(CONFIG_RTL_USB_IP_HOST_SPEEDUP),y)
COMMON_CFLAGS += -DRTL_USB_IP_HOST_SPEEDUP
COMMON_CFLAGS += -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DENABLE_LFS
endif

ifeq ($(CONFIG_RTL_STP),y)
COMMON_CFLAGS += -DCONFIG_RTL_STP
endif

ifeq ($(CONFIG_BASEON_SCHEDULE_FILTER),y)
COMMON_CFLAGS += -DCONFIG_SCH_FILTER
endif

ifneq ($(CONFIG_APP_APPLE_MFI_WAC),y)
ifeq ($(CONFIG_IPV6),y)
COMMON_CFLAGS += -DCONFIG_IPV6

ifeq ($(CONFIG_APP_NDP_PROXY),y)
COMMON_CFLAGS += -DCONFIG_APP_NDP_PROXY
endif
endif
endif

ifeq ($(CONFIG_IPV6_CE_ROUTER_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_IPV6_CE_ROUTER_SUPPORT
endif

ifeq ($(CONFIG_IPV6_RA_RDNSS_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_IPV6_RA_RDNSS_SUPPORT
ifeq ($(CONFIG_IPV6_RA_DNSSL_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_IPV6_RA_DNSSL_SUPPORT
endif
endif

ifeq ($(CONFIG_RTL_819X),y)
COMMON_CFLAGS += -DCONFIG_RTL_819X
endif

ifeq ($(CONFIG_RTL_819XD),y)
COMMON_CFLAGS += -DCONFIG_RTL_819XD
endif
ifeq ($(CONFIG_RTL_8196B_GW),y)
COMMON_CFLAGS += -DCONFIG_RTL_8196B
endif

ifeq ($(CONFIG_RTL_8196C_GW),y)
COMMON_CFLAGS += -DCONFIG_RTL_8196C
endif

ifeq ($(CONFIG_RTL_8198C),y)
COMMON_CFLAGS += -DCONFIG_RTL_8198C
endif

ifeq ($(CONFIG_DSLITE_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_DSLITE_SUPPORT
endif

ifeq ($(CONFIG_SIXRD_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_SIXRD_SUPPORT
endif

ifeq ($(CONFIG_APP_RADVD),y)
ifeq ($(CONFIG_APP_RADVD_WAN),y)
COMMON_CFLAGS += -DCONFIG_APP_RADVD_WAN
endif
endif

ifeq ($(CONFIG_RTL_8198_GW),y)
COMMON_CFLAGS += -DCONFIG_RTL_8198
endif

ifeq ($(CONFIG_RTL_8198_AP_ROOT),y)
COMMON_CFLAGS += -DCONFIG_RTL_8198 -DCONFIG_RTL_8198_AP_ROOT
ifdef CONFIG_8198_PORT5_GMII
COMMON_CFLAGS += -DGMII_ENABLED
endif
endif
ifeq ($(CONFIG_APP_WEAVE),y)
COMMON_CFLAGS += -DCONFIG_APP_WEAVE
endif
ifeq ($(CONFIG_APP_ZIGBEE),y)
COMMON_CFLAGS += -DCONFIG_APP_ZIGBEE
endif
ifeq ($(CONFIG_RTL_8197D_AP),y)
COMMON_CFLAGS += -DCONFIG_RTL_8197D_AP
endif

ifeq ($(CONFIG_RTL_AP_PACKAGE),y)
COMMON_CFLAGS += -DCONFIG_RTL_AP_PACKAGE
endif

ifeq ($(CONFIG_RTL_819XD),y)
COMMON_CFLAGS += -DCONFIG_RTL_819XD
endif

ifeq ($(CONFIG_RTL_8196E),y)
COMMON_CFLAGS += -DCONFIG_RTL_8196E
endif

ifeq ($(CONFIG_RTL_8197F),y)
COMMON_CFLAGS += -DCONFIG_RTL_8197F
endif

ifeq ($(CONFIG_RTL_8197F),y)
ifeq ($(CONFIG_USE_PCIE_SLOT_0),y)
COMMON_CFLAGS += -DFOR_DUAL_BAND
endif
endif

ifeq ($(CONFIG_RTL_8198B),y)
COMMON_CFLAGS += -DCONFIG_RTL_8198B
endif

ifeq ($(CONFIG_POCKET_ROUTER_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_POCKET_ROUTER_SUPPORT
endif

ifeq ($(CONFIG_POCKET_AP_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_POCKET_AP_SUPPORT
endif

ifeq ($(CONFIG_DOMAIN_NAME_QUERY_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_DOMAIN_NAME_QUERY_SUPPORT
endif

ifeq ($(CONFIG_RTL_DFS_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_DFS_SUPPORT
endif

ifeq ($(CONFIG_RTL_CLIENT_MODE_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_WLAN_CLIENT_MODE
endif
 
ifeq ($(CONFIG_RTL_REPEATER_MODE_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_WLAN_REPEATER_MODE
endif

ifeq ($(CONFIG_RTL_WDS_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_WLAN_WDS_SUPPORT
endif

ifeq ($(CONFIG_RTL_VAP_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_WLAN_VAP_SUPPORT
endif

ifeq ($(CONFIG_PCIE_POWER_SAVING),y)
COMMON_CFLAGS += -DPOWER_CONSUMPTION_SUPPORT
endif

ifeq ($(CONFIG_RTL_8196_SPI_FLASH),y)
COMMON_CFLAGS += -DCONFIG_RTL8196_SPI
endif

ifeq ($(CONFIG_RTL_WAPI_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_WAPI_SUPPORT
ifeq ($(CONFIG_RTL_WAPI_LOCAL_AS_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_WAPI_LOCAL_AS_SUPPORT
endif
endif

ifeq ($(CONFIG_APP_IAPP),y)
COMMON_CFLAGS += -DCONFIG_IAPP_SUPPORT
endif

ifeq ($(CONFIG_APP_RTK_INBAND_CTL), y)
COMMON_CFLAGS += -DSET_MIB_FROM_FILE
COMMON_CFLAGS += -DCONFIG_APP_RTK_INBAND_CTL
endif

ifeq ($(CONFIG_RTL_802_1X_CLIENT_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_802_1X_CLIENT_SUPPORT
endif
ifeq ($(CONFIG_RTL_ETH_802DOT1X_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_ETH_802DOT1X_SUPPORT
endif
ifeq ($(CONFIG_RTL_ETH_802DOT1X_CLIENT_MODE_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_ETH_802DOT1X_CLIENT_MODE_SUPPORT
endif
#add mld snooping support
ifeq ($(CONFIG_IGMPV3_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_IGMPV3_SUPPORT
endif

#add mld snooping support
ifeq ($(CONFIG_RTL_MLD_SNOOPING),y)
COMMON_CFLAGS += -DCONFIG_RTL_MLD_SNOOPING
endif

ifeq ($(CONFIG_RTL_COMAPI_CFGFILE),y)
COMMON_CFLAGS += -DCONFIG_IWPRIV_INTF
COMMON_CFLAGS += -DCONFIG_RTL_COMAPI_CFGFILE
endif

COMMON_CFLAGS += -DCONFIG_FLASH_SIZE=$(CONFIG_RTL_FLASH_SIZE)

ifeq ($(CONFIG_RTL_FLASH_MAPPING_ENABLE),y)
COMMON_CFLAGS += -DCONFIG_RTL_FLASH_MAPPING_ENABLE
ifdef CONFIG_RTL_HW_SETTING_OFFSET
COMMON_CFLAGS += -DCONFIG_RTL_HW_SETTING_OFFSET=$(CONFIG_RTL_HW_SETTING_OFFSET)
endif

ifdef CONFIG_RTL_DEFAULT_SETTING_OFFSET
COMMON_CFLAGS += -DCONFIG_RTL_DEFAULT_SETTING_OFFSET=$(CONFIG_RTL_DEFAULT_SETTING_OFFSET)
endif

ifdef CONFIG_RTL_CURRENT_SETTING_OFFSET
COMMON_CFLAGS += -DCONFIG_RTL_CURRENT_SETTING_OFFSET=$(CONFIG_RTL_CURRENT_SETTING_OFFSET)
endif

ifdef CONFIG_RTL_WEB_PAGES_OFFSET
COMMON_CFLAGS += -DCONFIG_RTL_WEB_PAGES_OFFSET=$(CONFIG_RTL_WEB_PAGES_OFFSET)
endif

ifdef CONFIG_RTL_LINUX_IMAGE_OFFSET  
COMMON_CFLAGS += -DCONFIG_RTL_CODE_IMAGE_OFFSET=$(CONFIG_RTL_LINUX_IMAGE_OFFSET)
endif

ifdef CONFIG_RTL_ROOT_IMAGE_OFFSET 
COMMON_CFLAGS += -DCONFIG_RTL_ROOT_IMAGE_OFFSET=$(CONFIG_RTL_ROOT_IMAGE_OFFSET)
endif
endif

ifeq ($(CONFIG_ISP_IGMPPROXY_MULTIWAN),y)
COMMON_CFLAGS += -DCONFIG_ISP_IGMPPROXY_MULTIWAN
endif

ifeq ($(CONFIG_RTL_MULTI_LAN_DEV),y)
COMMON_CFLAGS += -DCONFIG_RTL_MULTI_LAN_DEV
endif

ifeq ($(CONFIG_RTL_IP_POLICY_ROUTING_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_IP_POLICY_ROUTING_SUPPORT
endif

ifeq ($(CONFIG_RTL_HW_NAPT), y)
COMMON_CFLAGS += -DCONFIG_RTL_HW_NAPT
endif

ifeq ($(CONFIG_RTL_LAYERED_DRIVER_ACL),y)
COMMON_CFLAGS += -DCONFIG_RTL_LAYERED_DRIVER_ACL
endif

ifeq ($(CONFIG_RTK_VLAN_SUPPORT), y)
COMMON_CFLAGS += -DCONFIG_RTK_VLAN_SUPPORT
endif

ifeq ($(CONFIG_RTK_VLAN_WAN_TAG_SUPPORT), y)
COMMON_CFLAGS += -DCONFIG_RTK_VLAN_WAN_TAG_SUPPORT
endif

ifeq ($(CONFIG_RTK_BRIDGE_VLAN_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTK_BRIDGE_VLAN_SUPPORT
endif
ifeq ($(CONFIG_RTL_HW_VLAN_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_HW_VLAN_SUPPORT
endif
# For mini_upnp stand alone
COMMON_CFLAGS += -DSTAND_ALONE_MINIUPNP

ifeq ($(CONFIG_RTL_92D_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_92D_SUPPORT 
endif

ifeq ($(CONFIG_RTL_8812_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_8812_SUPPORT 
endif

ifeq ($(CONFIG_RTL_AC2G_256QAM),y)
COMMON_CFLAGS += -DCONFIG_RTL_AC2G_256QAM
endif

ifeq ($(CONFIG_RTL_8812AR_VN_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_8812AR_VN_SUPPORT
endif
ifeq ($(CONFIG_RTL_8812_1T1R_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_8812_1T1R_SUPPORT
endif

ifeq ($(CONFIG_RTL_8814_8194_2T2R_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_8814_8194_2T2R_SUPPORT
endif


ifeq ($(CONFIG_RTL_92D_DMDP),y)
COMMON_CFLAGS += -DCONFIG_RTL_92D_DMDP
endif

ifeq ($(CONFIG_ENABLE_EFUSE),y)
COMMON_CFLAGS += -DWLAN_MAC_FROM_EFUSE
endif

ifeq ($(CONFIG_RTL_FAST_FILTER), y)
COMMON_CFLAGS += -DCONFIG_RTL_FAST_FILTER 
endif

ifeq ($(CONFIG_BAND_2G_ON_WLAN0), y)
COMMON_CFLAGS += -DCONFIG_BAND_2G_ON_WLAN0
endif

ifeq ($(CONFIG_BAND_5G_ON_WLAN0), y)
COMMON_CFLAGS += -DCONFIG_BAND_5G_ON_WLAN0
endif

#ifeq ($(CONFIG_RTL_DUAL_PCIESLOT_BIWLAN),y)
ifeq ($(CONFIG_USE_PCIE_SLOT_0),y)
ifeq ($(CONFIG_USE_PCIE_SLOT_1),y)
ifeq ($(CONFIG_SLOT_0_92C),y)
ifeq ($(CONFIG_SLOT_1_92C),y)
COMMON_CFLAGS += -DCONFIG_RTL_DUAL_PCIESLOT_BIWLAN
endif
endif
endif
endif

ifeq ($(CONFIG_APP_REINIT),y)
COMMON_CFLAGS += -DRTK_REINIT_SUPPORT
endif
ifeq ($(CONFIG_RTL_WLAN_DOS_FILTER),y)
COMMON_CFLAGS += -DCONFIG_RTL_WLAN_DOS_FILTER
endif

#ifeq ($(CONFIG_APP_APPLE_MFI_WAC),y)
#COMMON_CFLAGS += -DWAC_CONFIGURING_REPEATER
#endif


#zj: add for QoS
ifeq ($(GW),1)
GATEWAY += -DENABLE_QOS
GATEWAY += -DQOS_BY_BANDWIDTH
endif

ifeq ($(CONFIG_NETFILTER_XT_MATCH_LAYER7),y)
GATEWAY += -DCONFIG_NETFILTER_XT_MATCH_LAYER7
endif

ifeq ($(CONFIG_APP_FWD),y)
COMMON_CFLAGS += -DCONFIG_APP_FWD
endif

ifeq ($(CONFIG_APP_BOA_NEW_UI),y)
COMMON_CFLAGS += -DCONFIG_APP_BOA_NEW_UI
endif
ifeq ($(CONFIG_APP_BOA_AUTO_RECOVER),y)
COMMON_CFLAGS += -DCONFIG_APP_BOA_AUTO_RECOVER
endif
#Multi-users
ifeq ($(CONFIG_APP_MULTI_USERS),y)
COMMON_CFLAGS += -DSUPER_NAME_SUPPORT
endif

ifeq ($(CONFIG_DIGEST_AUTHENTICATION),y)
COMMON_CFLAGS += -DDIGEST_AUTHENTICATION
endif

ifeq ($(CONFIG_APP_WSC), y)
COMMON_CFLAGS += -DWIFI_SIMPLE_CONFIG_SUPPORT
endif

ifeq ($(CONFIG_APP_TR069),y)
COMMON_CFLAGS += -DCONFIG_APP_TR069
COMMON_CFLAGS += -D_PRMT_X_TELEFONICA_ES_DHCPOPTION_
COMMON_CFLAGS += -DSUPPORT_RESERVED_DHCP_IPADDR
ifeq ($(CONFIG_RTL_CWMP_TRANSFER_PARTITION_SIZE), )
$(warning "CONFIG_RTL_CWMP_TRANSFER_PARTITION_SIZE is NOT defined!!")
COMMON_CFLAGS += -DCONFIG_RTL_CWMP_TRANSFER_PARTITION_SIZE=0
else
COMMON_CFLAGS += -DCONFIG_RTL_CWMP_TRANSFER_PARTITION_SIZE=$(CONFIG_RTL_CWMP_TRANSFER_PARTITION_SIZE)
endif
ifeq ($(CONFIG_RTL_CWMP_NOTIFICATION_PARTITION_SIZE), )
$(warning "CONFIG_RTL_CWMP_NOTIFICATION_PARTITION_SIZE is NOT defined!!")
COMMON_CFLAGS += -DCONFIG_RTL_CWMP_NOTIFICATION_PARTITION_SIZE=0
else
COMMON_CFLAGS += -DCONFIG_RTL_CWMP_NOTIFICATION_PARTITION_SIZE=$(CONFIG_RTL_CWMP_NOTIFICATION_PARTITION_SIZE)
endif

ifeq ($(CONFIG_USER_CWMP_WITH_SSL),y)
COMMON_CFLAGS += -D_CWMP_WITH_SSL_ -DCWMP_ENABLE_SSL

ifeq ($(CONFIG_USER_CWMP_WITH_MATRIXSSL), y)
COMMON_CFLAGS += -DCONFIG_USER_CWMP_WITH_MATRIXSSL -D_WITH_MATRIXSSL_
endif

ifeq ($(CONFIG_USER_CWMP_WITH_OPENSSL), y)
COMMON_CFLAGS += -DCONFIG_USER_CWMP_WITH_OPENSSL -DWITH_OPENSSL
ifeq ($(CONFIG_USER_CWMP_DYNAMIC_SERV_AUTH), y)
COMMON_CFLAGS += -DCWMP_DYNAMIC_SERV_AUTH
endif
endif#endifCONFIG_USER_CWMP_WITH_OPENSSL

endif#endif CONFIG_USER_CWMP_WITH_SSL

ifneq ($(CONFIG_MTD_CHAR), y)
ifeq ($(KERNEL_VER),linux-2.6.30)
$(error You have to turn on the kernel option "CONFIG_MTD_CHAR" for TR069)
endif
endif

ifeq ($(CONFIG_USER_CWMP_WITH_TR098), y)
COMMON_CFLAGS += -DCONFIG_USER_CWMP_WITH_TR098
COMMON_CFLAGS += -D_PRMT_DEVICECONFIG_ -DTIME_ZONE -D_PRMT_USERINTERFACE_
endif

ifeq ($(CONFIG_USER_CWMP_WITH_TR143),y)
COMMON_CFLAGS += -DCONFIG_USER_CWMP_WITH_TR143
COMMON_CFLAGS += -D_PRMT_CAPABILITIES_
endif

ifeq ($(CONFIG_USER_CWMP_WITH_TR181), y)
COMMON_CFLAGS += -DCONFIG_USER_CWMP_WITH_TR181 -D_PRMT_USERINTERFACE_
endif

ifeq ($(CONFIG_USER_CWMP_WITH_TR069_ANNEX_G), y)
COMMON_CFLAGS += -DTR069_ANNEX_G
endif

ifeq ($(CONFIG_USER_CWMP_WITH_TR181_V6), y)
COMMON_CFLAGS += -DTR181_V6_SUPPORT
endif

ifeq ($(CONFIG_USER_CWMP_WITH_TR143),y)
COMMON_CFLAGS += -DCONFIG_USER_CWMP_WITH_TR143 -D_PRMT_TR143_
endif

ifeq ($(CONFIG_USER_CWMP_WHTH_TR098_QOS),y)
COMMON_CFLAGS += -D_STD_QOS_ -DQOS_OF_TR069
endif

endif#end ifeq CONFIG_APP_TR069, y

ifdef CONFIG_RTL_WEBPAGES_IN_ROOTFS
COMMON_CFLAGS += -DCONFIG_RTL_WEBPAGES_IN_ROOTFS
endif

ifdef CONFIG_APP_AUTH_2NDSRV
COMMON_CFLAGS += -DCONFIG_APP_AUTH_2NDSRV
endif

ifeq ($(GW),1)
COMMON_CFLAGS += $(GATEWAY)
endif

ifeq ($(CONFIG_RTL_SUPPORT_MULTI_PROFILE),y)
COMMON_CFLAGS += -DWLAN_PROFILE
endif

ifeq ($(CONFIG_APP_MINIIGD-1.8),y)
COMMON_CFLAGS += -DUSE_MINIUPNPD_V1.8
endif

ifeq ($(CONFIG_APP_EBTABLES),y)
COMMON_CFLAGS += -DCONFIG_APP_EBTABLES
endif

ifeq ($(CONFIG_APP_SMTP_CLIENT),y)
COMMON_CFLAGS += -DCONFIG_APP_SMTP_CLIENT
endif

ifeq ($(CONFIG_APP_RTK_VOIP),y)
PWD := $(shell pwd)
ifeq ($(CONFIG_APP_RTK_VOIP_E8C),y)
export VOIP_APP = $(PWD)/rtk_voip-e8c
else
ifdef CONFIG_RTK_VOIP_DRIVERS_PCM89xxE
export VOIP_APP = $(PWD)/boa/../rtk_voip-89xxE
else
export VOIP_APP = $(PWD)/rtk_voip
endif
endif
COMMON_CFLAGS += -DVOIP_SUPPORT -I$(VOIP_APP)/includes -I$(VOIP_APP)/web -I$(PWD) -I$(PWD)/boa
ifdef CONFIG_RTK_VOIP_PACKAGE_867X
COMMON_CFLAGS += -DATA867x
endif
ifdef CONFIG_RTK_VOIP_IP_PHONE
COMMON_CFLAGS += -I$(VOIP_APP)/ui/include
endif
endif

ifdef CONFIG_EBTABLES_KERNEL_SUPPORT
COMMON_CFLAGS += -DCONFIG_EBTABLES_KERNEL_SUPPORT
endif

ifndef CONFIG_RTL_AP
COMMON_CFLAGS += -DSEND_GRATUITOUS_ARP
endif
ifeq ($(CONFIG_APP_CPU_UTILIZATION), y)
COMMON_CFLAGS += -DCONFIG_CPU_UTILIZATION
endif
ifeq ($(CONFIG_SUPPORT_RUSSIA_FEATURES),y)
COMMON_CFLAGS += -DSUPPORT_ZIONCOM_RUSSIA
endif

ifeq ($(CONFIG_APP_APPLE_MFI_WAC),y)
COMMON_CFLAGS += -DCONFIG_APP_APPLE_MFI_WAC
ifeq ($(CONFIG_APP_APPLE_HOMEKIT),y)
COMMON_CFLAGS += -DCONFIG_APP_APPLE_HOMEKIT
endif
endif

ifeq ($(CONFIG_APP_RADVD),y)
ifeq ($(CONFIG_IPV6_CE_ROUTER_SUPPORT),y)
COMMON_CFLAGS += -DSUPPORT_RDNSS_OPTION -DSUPPORT_DNSSL_OPTION
endif
ifeq ($(CONFIG_IPV6_DNSV6_MODE_SUPPORT),y)
COMMON_CFLAGS += -DSUPPORT_RDNSS_OPTION -DSUPPORT_DNSSL_OPTION
endif
endif

ifeq ($(CONFIG_IPV6_CE_ROUTER_SUPPORT),y)
COMMON_CFLAGS += -DSUPPORT_DEFEAT_IP_SPOOL_DOS 
endif

ifeq ($(CONFIG_IPV6_DNSV6_MODE_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_IPV6_DNSV6_MODE_SUPPORT
endif

ifeq ($(CONFIG_RTL_HARDWARE_IPV6_SUPPORT),y)
COMMON_CFLAGS += -DCONFIG_RTL_HARDWARE_IPV6_SUPPORT
endif

ifeq ($(CONFIG_RTL_FAST_IPV6),y)
COMMON_CFLAGS += -DCONFIG_RTL_FAST_IPV6
endif

ifeq ($(CONFIG_APP_CAPWAP),y)
COMMON_CFLAGS += -DRTK_CAPWAP
endif

ifeq ($(CONFIG_RTL_USERSPACE_WTDOG),y)
COMMON_CFLAGS += -DAPP_WATCHDOG
endif
ifdef CONFIG_RTL_NO_BR_SHORTCUT
ifneq ($(CONFIG_RTL_NO_BR_SHORTCUT),y)
COMMON_CFLAGS += -DCONFIG_RTL_BR_SHORTCUT_SUPPORT
endif
endif
ifeq ($(CONFIG_APP_UBUS),y)
COMMON_CFLAGS += -DJSONC
endif
ifeq ($(CONFIG_APP_BLUEZ),y)
COMMON_CFLAGS += -DCONFIG_APP_BLUEZ
endif
ifeq ($(CONFIG_APP_BT_MP),y)
COMMON_CFLAGS += -DCONFIG_APP_BT_MP
endif
ifeq ($(CONFIG_APP_BT_REPEATER_CONFIG),y)
COMMON_CFLAGS += -DCONFIG_APP_BT_REPEATER_CONFIG
endif
ifeq ($(CONFIG_SERIAL_BLUETOOTH),y)
COMMON_CFLAGS += -DCONFIG_SERIAL_BLUETOOTH
endif
ifeq ($(CONFIG_USB_BLUETOOTH),y)
COMMON_CFLAGS += -DCONFIG_USB_BLUETOOTH
endif
ifeq ($(CONFIG_RTK_BLUETOOTH_HW_RTL8822B_S),y)
COMMON_CFLAGS += -DCONFIG_RTK_BLUETOOTH_HW_RTL8822B_S
endif
ifeq ($(CONFIG_RTK_BLUETOOTH_HW_RTL8761A_S),y)
COMMON_CFLAGS += -DCONFIG_RTK_BLUETOOTH_HW_RTL8761A_S
endif
ifeq ($(CONFIG_RTL_COMAPI_WLTOOLS), y)
COMMON_CFLAGS += -DCONFIG_RTL_COMAPI_WLTOOLS
endif
#------------------------------------------------------------------------------
# Export variables
#------------------------------------------------------------------------------
export COMMON_CFLAGS
export APMIB_SHARED
export APMIB_LIB


