#obj-y += lc_ltencm.o

obj-y = ncm.o

ncm-y = lte-ncm.o partialbuf.o dhcp.o arp.o filter.o dhcp_dev_info.o dhcpv6.o icmpv6.o ipv6.o

#obj-y = lte-ncm.o partialbuf.o dhcp.o arp.o filter.o dhcp_dev_info.o dhcpv6.o icmpv6.o ipv6.o

#KERN_DIR:=/lib/modules/$(shell uname -r)/build
# KERN_DIR:=/home/ybjiang/linux-2.6.31


#EXTRA_CFLAGS += --save-temps

#KDIR = $(DIR_LINUX)

#all:
#	make -C $(KDIR) M=`pwd` modules 
	#make -C $(KERN_DIR) M=$(PWD) modules ARCH=mips  CROSS_COMPILE=mips-linux-

#clean:
#	make -C $(KERN_DIR) M=$(PWD) clean

#romfs:
#	cp lc_ltencm.ko /home/winfred_wang/trunk_code/release-rtl819x-sdk-v3.4.7.3-31833-20150520/target/romfs
	#$(ROMFSINST) /bin/lc_ltencm.o

#distclean:
#	rm *.mod.c *.o *.ko modules.order Module.*


